name: sphinx

on: [push, workflow_call]

jobs:
  spellcheck:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-uv@v5
        with:
          python-version: "3.12"
      - name: install requirements
        run: uv sync --extra dev
      - name: run pytest
        run: uv run pytest
      - name: run spellcheck
        run: uv run sphinx-build -E -a -W --keep-going -b spelling doc _build
  build:
    uses: ISISComputingGroup/reusable-workflows/.github/workflows/sphinx.yml@main
    secrets: inherit
    with:
      deploy-branch: "master"
