name: sphinx

on: [push, workflow_call]

jobs:
  spellcheck:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
      - name: install requirements
        run: uv pip install -e .[dev]
      - name: run pytest
        run: python -m pytest
      - name: run spellcheck
        run: sphinx-build -E -a -W --keep-going -b spelling doc _build
  build:
    uses: ISISComputingGroup/reusable-workflows/.github/workflows/sphinx.yml@main
    secrets: inherit
    with:
      deploy-branch: "master"
